---
title: "热图"
output: html_document
---
1. 准备数据
```{r}
library(ComplexHeatmap)
library(circlize)
library(stringr)

d<-read.csv(file = "E:/data_melanoma/net_mapped_with_DESeq2.csv",header = TRUE)
d<-d[,c("hgnc_symbol","ensembl","Number_of_Samples_Mutations","CNA","Number_of_Samples_CNA","log2FoldChange")]
d<-d[!duplicated(d),]

glist1<-d[order(d$Number_of_Samples_Mutations,decreasing = TRUE),"hgnc_symbol"]
glist1<-glist1[!duplicated(glist1)]
#Number_of_Samples_Mutations最高的前10个基因
glist1a<-glist1[1:20]
#Number_of_Samples_Mutations最高的前200个基因
glist1b<-glist1[1:200]

glist2<-d[order(d$Number_of_Samples_CNA,decreasing = TRUE),"hgnc_symbol"]
glist2<-glist2[!duplicated(glist2)]
#Number_of_Samples_CNA最高的前10个基因
glist2a<-glist2[1:20]
#Number_of_Samples_CNA最高的前200个基因
glist2b<-glist2[1:200]

glist3<-d[order(abs(d$log2FoldChange),decreasing = TRUE),"hgnc_symbol"]
glist3<-glist3[!duplicated(glist3)]
#log2FoldChange绝对值最高的前10个基因
glist3a<-glist3[1:20]
#log2FoldChange绝对值最高的前200个基因
glist3b<-glist3[1:200]

guni<-union(glist1a,union(glist2a,glist3a))
gint<-intersect(glist1b,intersect(glist2b,glist3b))

dataSmNT<-read.csv("E:/data_melanoma/TCGA_SKCM_dataSmNT.csv",header = TRUE)#1
dataSmNT$sample_type<-paste0("NT",1:nrow(dataSmNT))
dataSmTP<-read.csv("E:/data_melanoma/TCGA_SKCM_dataSmTP.csv",header = TRUE)#103
dataSmTP$sample_type<-paste0("TP",1:nrow(dataSmTP))
dataSmTM<-read.csv("E:/data_melanoma/TCGA_SKCM_dataSmTM.csv",header = TRUE)#368
dataSmTM$sample_type<-paste0("TM",1:nrow(dataSmTM))
dataSmTAM<-read.csv("E:/data_melanoma/TCGA_SKCM_dataSmTAM.csv",header = TRUE)#1
dataSmTAM$sample_type<-paste0("TAM",1:nrow(dataSmTAM))

#TCGA samples
dataSm<-rbind(dataSmNT,dataSmTP,dataSmTM,dataSmTAM)
colnames(dataSm)[1]<-"sample_id"

#TCGA expression data
expNorm<-read.csv("E:/data_melanoma/skcm_exp_TCGA_norm.csv",header = TRUE,check.names = FALSE,row.names = 1)

mat1<-matrix(nrow = length(guni),ncol = nrow(dataSm),dimnames = list(guni,dataSm$sample_type))
for(i in 1:nrow(mat1)){
  for(j in 1:ncol(mat1)){
    mat1[i,j]<-log10(expNorm[guni[i],dataSm$sample_id[j]]+0.1)
  }
}
write.csv(mat1,"E:/data_melanoma/前20基因并集.csv")

mat2<-matrix(nrow = length(gint),ncol = nrow(dataSm),dimnames = list(gint,dataSm$sample_type))
for(i in 1:nrow(mat2)){
  for(j in 1:ncol(mat2)){
    mat2[i,j]<-log10(expNorm[guni[i],dataSm$sample_id[j]]+0.1)
  }
}
write.csv(mat2,"E:/data_melanoma/前200基因交集.csv")
```

2. 画20个基因并集热图
```{r}
col_fun1<-colorRamp2(c(min(mat1,na.rm = TRUE),median(mat1,na.rm = TRUE),max(mat1,na.rm = TRUE)),c("green","white","purple"));
mat1<-na.omit(mat1)
dend1 = hclust(dist(mat1,method = "euclidean"))
pdf("heatmap_gene_union_hclust.pdf");
ha1 = HeatmapAnnotation(type = factor(str_extract(colnames(mat1),"[A-Z]+")),col = list(type = c("TAM"="gray","NT"="black","TM"="brown2","TP"="green3")),annotation_legend_param = list(
  title = "Patient Type",
  at = c("TAM","NT","TM","TP"),
  labels = c("Additional Metastatic","Solid Tissue Normal","Metastatic","Primary Solid Tumor")
));
ht1 = Heatmap(mat1,
        col = col_fun1,
        name = "log10(read count+0.1)",
        na_col = "black",
        border = TRUE,
        row_names_gp = gpar(fontsize = 8),
        column_names_gp = gpar(fontsize = 8),
        # column_km = 2,
        # column_km_repeats = 100,
        cluster_columns = dend1,
        column_split = 2,
        # column_split = factor(str_extract(colnames(mat1),"[A-Z]+")),
        show_parent_dend_line = FALSE,
        column_title_gp = gpar(fontsize = 8),
        column_gap = unit(2,"mm"),
        # show_column_names = FALSE,
        # show_column_dend = FALSE,
        heatmap_legend_param = list(
          at = c(min(mat1,na.rm = TRUE),median(mat1,na.rm = TRUE),max(mat1,na.rm = TRUE)),
          labels = c("low","median","high"),
          title = "log10(read count+0.1)",
          legend_height = unit(4, "cm"),
          legend_direction = c("horizontal")),
        top_annotation = ha1,
        );
draw(ht1,
     heatmap_legend_side = "bottom",
     annotation_legend_side = "bottom",
     merge_legend = TRUE,
     );
dev.off()
```

3. 画200个基因交集热图
```{r}
col_fun2<-colorRamp2(c(min(mat2,na.rm = TRUE),median(mat2,na.rm = TRUE),max(mat2,na.rm = TRUE)),c("green","white","purple"));
mat2<-na.omit(mat2);
pdf("heatmap_gene_intersect_kmeans.pdf");
dend2 = hclust(dist(mat2,method = "euclidean"));
ha2 = HeatmapAnnotation(type = factor(str_extract(colnames(mat1),"[A-Z]+")),col = list(type = c("TAM"="gray","NT"="black","TM"="brown2","TP"="green3")),annotation_legend_param = list(
  title = "Patient Type",
  at = c("TAM","NT","TM","TP"),
  labels = c("Additional Metastatic","Solid Tissue Normal","Metastatic","Primary Solid Tumor")
));
ht2 = Heatmap(mat2,
        col = col_fun2,
        name = "log10(read count+0.1)",
        na_col = "black",
        border = TRUE,
        column_names_gp = gpar(fontsize = 8),
        column_km = 2,
        column_km_repeats = 100,
        # cluster_columns = dend2,
        # column_split = 2,
        # column_split = factor(str_extract(colnames(mat1),"[A-Z]+")),
        show_parent_dend_line = FALSE,
        column_title_gp = gpar(fontsize = 8),
        column_gap = unit(2,"mm"),
        show_column_names = FALSE,
        # show_column_dend = FALSE,
        heatmap_legend_param = list(
          at = c(min(mat2,na.rm = TRUE),median(mat2,na.rm = TRUE),max(mat2,na.rm = TRUE)),
          labels = c("low","median","high"),
          title = "log10(read count+0.1)",
          legend_height = unit(4, "cm"),
          legend_direction = c("horizontal")),
        top_annotation = ha2,
        );
draw(ht2,
     heatmap_legend_side = "bottom",
     annotation_legend_side = "bottom",
     merge_legend = TRUE,
     );
dev.off()
```

