---
title: "生存分析"
output: html_document
---

1.准备数据
```{r}
library(RTCGA.clinical)#survival times
library(TCGAbiolinks)
library(SummarizedExperiment)
library(survminer)
library(survival)
#clinical data
SKCM.surv<-survivalTCGA(SKCM.clinical)
dim(SKCM.surv)#461,3
#expression data
dataNorm<-read.csv("E:/data_melanoma/skcm_exp_TCGA_norm.csv",header = TRUE,check.names = FALSE,row.names = 1)
colnames(dataNorm)<-substr(colnames(dataNorm),1,12)
  
surv_gene<-c("BRAF","CDKN2A","SPP1","TP53")
#BRAF has the higest Number_of_Samples_Mutations
#CDKN2A has the higest Number_of_Samples_CNA
#SPP1 has the higest log2FoldChange

SKCM.exp<-dataNorm[surv_gene,]
tp1<-which(SKCM.surv$bcr_patient_barcode %in% colnames(SKCM.exp)==F)

SKCM.surv$BRAF<-as.numeric(t(SKCM.exp["BRAF",SKCM.surv$bcr_patient_barcode]))
SKCM.surv$CDKN2A<-as.numeric(t(SKCM.exp["CDKN2A",SKCM.surv$bcr_patient_barcode]))
SKCM.surv$SPP1<-as.numeric(t(SKCM.exp["SPP1",SKCM.surv$bcr_patient_barcode]))
SKCM.surv$TP53<-as.numeric(t(SKCM.exp["TP53",SKCM.surv$bcr_patient_barcode]))

#determine the optimal cutpoint of variables
SKCM.surv.cut<-surv_cutpoint(SKCM.surv,time = "times", event = "patient.vital_status", variables = c("BRAF","CDKN2A","SPP1","TP53"))

SKCM.surv.cat<-surv_categorize(SKCM.surv.cut)
```

2.对BRAF, CDKN2A, SPP1, TP53分别进行生存分析
```{r}
pdf("ggsurv_cutpoint_TP53.pdf",onefile = FALSE);
fit<-surv_fit(Surv(times,patient.vital_status)~TP53,data = SKCM.surv.cat);
ggsurvplot(fit,
           risk.table = TRUE,
           pval = TRUE,
           conf.int = TRUE,
           break.time.by = 2000,
           ggtheme = theme_RTCGA(),
           xlab = "Time(day)",
           legend = "top",
           legend.title = "TP53",
           );
dev.off()
```

3.四个基因一起生存分析
```{r}
pdf("ggsurv_cutpoint_Survival_BRAF_CDKN2A_SPP1_TP53.pdf",onefile = FALSE);
fit<-surv_fit(Surv(times,patient.vital_status)~BRAF+CDKN2A+SPP1+TP53,data = SKCM.surv.cat);
ggsurvplot(fit,
           risk.table = TRUE,
           palette = palette(c("red","orange","yellow","purple","pink","brown","darkgreen","green","lightgreen","blue","steelblue","cyan","gray","dimgray","black")),
           pval = TRUE,
           conf.int = FALSE,
           break.time.by = 2000,
           ggtheme = theme_RTCGA(),
           xlab = "Time(day)",
           legend = "top",
           legend.title = "BRAF+CDKN2A+SPP1+TP53",
           legend.labs = c("HHHH","HHHL","HHLH","HHLL","HLHH","HLLH","HLLL","LHHH","LHHL","LHLH","LHLL","LLHH","LLHL","LLLH","LLLL"),
           risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE,
           fontsize = 3,
           risk.table.height = 0.4,
           );
dev.off()
```
