---
title: "生存分析"
output: html_document
---

1.准备数据
```{r}
library(RTCGA.clinical)#survival times
library(RTCGA.mutations)
library(tidyverse)
library(survminer)
library(survival)
#clinical data
SKCM.surv<-survivalTCGA(SKCM.clinical)
dim(SKCM.surv)#461,3
#expression data
dataNorm<-read.csv("E:/data_melanoma/skcm_exp_TCGA_norm.csv",header = TRUE,check.names = FALSE,row.names = 1)
colnames(dataNorm)<-substr(colnames(dataNorm),1,12)
#mutations data
dataMutations<-mutationsTCGA(SKCM.mutations)
dataMutations$bcr_patient_barcode<-substr(dataMutations$bcr_patient_barcode,1,12)
dataMutations <- dataMutations %>% filter(Hugo_Symbol=="BRAF")
patient_Mutations <- dataMutations %>% dplyr::select(bcr_patient_barcode) %>% unique
patient_Mutations <- patient_Mutations %>% filter(bcr_patient_barcode %in% SKCM.surv$bcr_patient_barcode)#173
  
surv_gene<-c("BRAF","CDKN2A","TYRP1")
#BRAF has the higest Number_of_Samples_Mutations
#CDKN2A has the higest Number_of_Samples_CNA
#SPP1 has the higest log2FoldChange

#classify BRAF based on mutations information
SKCM.surv$BRAF[SKCM.surv$bcr_patient_barcode %in% patient_Mutations$bcr_patient_barcode ==TRUE]<-TRUE
SKCM.surv$BRAF[SKCM.surv$bcr_patient_barcode %in% patient_Mutations$bcr_patient_barcode ==FALSE]<-FALSE

SKCM.exp<-dataNorm[surv_gene[c(2,3)],]

tp1<-which(SKCM.surv$bcr_patient_barcode %in% colnames(SKCM.exp)==F)
SKCM.surv<-SKCM.surv[-tp1,]

SKCM.surv$CDKN2A<-as.numeric(t(SKCM.exp["CDKN2A",SKCM.surv$bcr_patient_barcode]))
SKCM.surv$TYRP1<-as.numeric(t(SKCM.exp["TYRP1",SKCM.surv$bcr_patient_barcode]))

#determine the optimal cutpoint of variables
SKCM.surv.cut<-surv_cutpoint(SKCM.surv,time = "times", event = "patient.vital_status", variables = c("BRAF","CDKN2A","TYRP1"))

SKCM.surv.cat<-surv_categorize(SKCM.surv.cut)
```

2.对BRAF, CDKN2A, TYRP1分别进行生存分析
```{r}
pdf("ggsurv_survival_CDKN2A_TYRP1.pdf",onefile = FALSE);
fit<-surv_fit(Surv(times,patient.vital_status)~CDKN2A+TYRP1,data = SKCM.surv.cat);
ggsurvplot(fit,
           risk.table = TRUE,
           pval = TRUE,
           conf.int = FALSE,
           break.time.by = 2000,
           ggtheme = theme_RTCGA(),
           xlab = "Time(day)",
           legend = "top",
           legend.title = "CDKN2A_TYRP1",
           risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE,
           font.legend = 6,
           );
dev.off()
```

3.三个基因一起生存分析
```{r}
pdf("ggsurv_survival_BRAF_CDKN2A_TYRP1.pdf",onefile = FALSE);
fit<-surv_fit(Surv(times,patient.vital_status)~BRAF+CDKN2A+TYRP1,data = SKCM.surv.cat);
ggsurvplot(fit,
           risk.table = TRUE,
           pval = TRUE,
           conf.int = FALSE,
           break.time.by = 2000,
           ggtheme = theme_RTCGA(),
           xlab = "Time(day)",
           legend = "top",
           legend.title = "BRAF_CDKN2A_TYRP1",
           risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE,
           fontsize = 4,
           font.legend = 4,
           );
dev.off()
```
